### ISSUE TITLE
BUTTON: 'Options' > 'Apply' and 'Ok' buttons are "greyed out"

### ISSUE THREAD

**Issue by aliascash** [shbli/spectre#6]
The 'Apply' and 'Ok' buttons are "greyed out" and will not work or be active after making changes
<img width="636" alt="screen shot 2018-04-16 at 23 00 13" src="https://user-images.githubusercontent.com/22733129/38837568-5cc89856-41ca-11e8-9d84-124dd6a143a0.png">

**Comment by shbli** [comment]
You have to change one of the options before clicking apply
